config/routes.rb
Inventory::Application.routes.draw do
  resources :server_applications


  authenticated :user do
    root :to => 'inventory_spreadsheets#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')


  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :my_account, :controller => :my_account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
    resources :jobs
  end

  resources :inventory_spreadsheets do
    member do
      get :new_email
      get :send_via_email
    end
    collection do
      get :generate
    end
  end

  resources :inventory_diagrams do
    member do
      get :new_email
      get :send_via_email
    end
    collection do
      get :generate
      get :show_generate
    end
  end
  resources :applications
  resources :application_versions
  resources :servers
  resources :application_family_applications
  resources :application_families
  resources :server_databases
  resources :databases
  resources :server_relationships
  resources :jobs
  resources :tenant_spaces
  resources :data_centers
  resources :environments
  resources :zones

  resources :audits

  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
    resources :jobs
  end

  namespace :api, defaults: {:format => :json} do
    root :to => 'versions#index'

    resources :versions

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :applications
      resources :application_versions
      resources :servers
      resources :jobs
      resources :inventory_spreadsheets do
        member do
          get :send_via_email
        end
        collection do
          get :generate
        end
      end
      resources :inventory_diagrams do
        member do
          get :send_via_email
        end
        collection do
          get :generate
        end
      end
    end
  end
end

app/models/server_relationship.rb
class ServerRelationship < ActiveRecord::Base
  attr_accessible :port, :server_primary_id, :server_secondary_id, :server_primary, :server_secondary, :description

  APP_INFO_END_POINT = 'server_relationships'

  belongs_to :server_primary, :foreign_key => :server_primary_id, :class_name => 'Server'
  belongs_to :server_secondary, :foreign_key => :server_secondary_id, :class_name => 'Server'
  has_and_belongs_to_many :inventory_spreadsheets

  validates :server_primary_id, :presence => true
  validates :server_secondary_id, :presence => true

  validates_uniqueness_of :server_primary_id, :scope => :server_secondary_id

  def self.create_and_update
    resources = appinfo_json_to_resources(AppInfo.retrieve_resources_json APP_CONFIG, APP_INFO_END_POINT)
    created_updated = Array.new

    if resources
      resources.each do |resource|
        current_resource = nil

        current_resource = ServerRelationship.find_by_server_primary_id_and_server_secondary_id_and_port(resource.server_primary.id, resource.server_secondary.id, resource.port) if resource.server_primary && resource.server_secondary && resource.port

        if current_resource
          # Exists
          unless (current_resource.server_primary.name == resource.server_primary.name) &&
              (current_resource.server_secondary.name == resource.server_secondary.name) &&
              (current_resource.port == resource.port) &&
              (current_resource.description == resource.description)
            # Needs updates
            current_resource.server_primary   = resource.server_primary unless current_resource.server_primary.name == resource.server_primary.name
            current_resource.server_secondary = resource.server_secondary unless current_resource.server_secondary.name == resource.server_secondary.name
            current_resource.port             = resource.port unless current_resource.port == resource.port
            current_resource.description      = resource.description unless current_resource.description == resource.description

            current_resource.save
            created_updated << current_resource
          end
        else
          # Doesn't exist
          resource.save
          created_updated << resource
        end
      end
    end

    created_updated
  end

  def self.remove_stale
    api_resources = appinfo_json_to_resources((AppInfo.retrieve_resources_json APP_CONFIG, APP_INFO_END_POINT))

    resources = all

    to_delete = Array.new

    resources.each do |resource|
      next unless resource.server_primary && resource.server_secondary

      to_delete << resource unless api_resources.any? {|r| (r.server_primary && r.server_secondary && ((r.server_primary.name.downcase == resource.server_primary.name.downcase) && (r.server_secondary.name.downcase == resource.server_secondary.name.downcase)) && r.port == resource.port)}
    end

    to_delete.each do |r|
      r.delete
    end

    to_delete
  end

  def diagram_edge_label
    label = "Port #{self.port.to_s}"

    "#{label} - #{self.description}" unless self.description.nil? || self.description.empty?
  end

  private
  def self.appinfo_json_to_resources(json)
    new_resources = Array.new

    json.each do |resource|
      next unless AppInfo.include?(APP_CONFIG, resource)

      server_primary    = Server.find_by_name(resource['server_primary']['name'])
      server_secondary  = Server.find_by_name(resource['server_secondary']['name'])

      next unless server_primary && server_secondary

      new_resources << new(
          :server_primary   => server_primary,
          :server_secondary => server_secondary,
          :port             => resource['port'],
          :description      => resource['description']
      )
    end

    new_resources
  end
end

app/controllers/server_relationships_controller.rb
class ServerRelationshipsController < ApplicationController
  load_and_authorize_resource

  before_filter :set_server_relationship, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @server_relationships = ServerRelationship.all
    respond_with(@server_relationships)
  end

  def show
    respond_with(@server_relationship)
  end

  def new
    @server_relationship = ServerRelationship.new
    respond_with(@server_relationship)
  end

  def edit
  end

  def create
    @server_relationship = ServerRelationship.new(params[:server_relationship])
    @server_relationship.save
    respond_with(@server_relationship)
  end

  def update
    @server_relationship.update_attributes(params[:server_relationship])
    respond_with(@server_relationship)
  end

  def destroy
    @server_relationship.destroy
    respond_with(@server_relationship)
  end

  private
    def set_server_relationship
      @server_relationship = ServerRelationship.find(params[:id])
    end
end

app/helpers/server_relationships_helper.rb
module ServerRelationshipsHelper
end

app/views/server_relationships/_form.html.erb
<%= form_for(@server_relationship) do |f| %>
  <% if @server_relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server_relationship.errors.count, "error") %> prohibited this server_relationship from being saved:</h2>

      <ul>
      <% @server_relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server_primary %><br />
    <%= f.collection_select :server_primary_id, Server.order(:name),:id,:name %>
  </div>
  <div class="field">
    <%= f.label :server_secondary %><br />
    <%= f.collection_select :server_secondary_id, Server.order(:name),:id,:name %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.number_field :port %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/server_relationships/edit.html.erb
<h1><%= t('general.editing') % "#{@server_relationship.server_primary.name} - #{@server_relationship.server_secondary.name}" %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Show', @server_relationship %> |
<%= link_to 'Back', server_relationships_path %>

app/views/server_relationships/index.html.erb
<h1><%= t('general.listing') % t('server_relationships.server_relationships') %></h1>

<table id='index_table' class='data_table'>
  <thead>
    <tr>
      <th><%= t('server_relationships.primary_server') %></th>
      <th><%= t('server_relationships.secondary_server') %></th>
      <th><%= t('server_relationships.port') %></th>
      <th><%= t('general.tables.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @server_relationships.each do |server_relationship| %>
    <tr>
      <td><%= server_relationship.server_primary.name %></td>
      <td><%= server_relationship.server_secondary.name %></td>
      <td><%= server_relationship.port %></td>
      <td>
        <%= link_to t('general.show'), server_relationship_path(server_relationship) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br />
<br />
<div>
  <%= t('general.download') %>: <%= link_to t('general.csv'), server_relationships_path(format: 'csv') %>
</div>

app/views/server_relationships/new.html.erb
<h1><%= t('general.new') % t('server_relationships.server_relationship') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', server_relationships_path %>

app/views/server_relationships/show.html.erb
<h1><%= t('server_relationships.server_relationship') %></h1>
<div class='model_info'>
  <b><%= t('server_relationships.primary_server') %></b>
  <%= link_to @server_relationship.server_primary.name, @server_relationship.server_primary %><br/>
  <b><%= t('server_relationships.secondary_server') %></b>
  <%= link_to @server_relationship.server_secondary.name, @server_relationship.server_secondary %><br/>
  <b><%= t('server_relationships.description') %>:</b>
  <%= @server_relationship.description %><br/>
  <b><%= t('server_relationships.port') %>:</b>
  <%= @server_relationship.port.to_s %><br/>
  <br />
  <b><%= t('general.created_on') %>:</b>
  <%= @server_relationship.created_at.to_formatted_s(:long_ordinal) %><br/>
  <b><%= t('general.updated_on') %>:</b>
  <%= @server_relationship.updated_at.to_formatted_s(:long_ordinal) %><br/><br/><br/>
</div>
<br/><br/><br/>

<%= link_to t('general.back'), :back %>