config/routes.rb
Inventory::Application.routes.draw do
  resources :server_applications


  authenticated :user do
    root :to => 'inventory_spreadsheets#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')


  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :my_account, :controller => :my_account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
    resources :jobs
  end

  resources :inventory_spreadsheets do
    member do
      get :new_email
      get :send_via_email
    end
    collection do
      get :generate
    end
  end

  resources :inventory_diagrams do
    member do
      get :new_email
      get :send_via_email
    end
    collection do
      get :generate
      get :show_generate
    end
  end
  resources :applications
  resources :application_versions
  resources :servers
  resources :application_family_applications
  resources :application_families
  resources :server_databases
  resources :databases
  resources :server_relationships
  resources :jobs
  resources :tenant_spaces
  resources :data_centers
  resources :environments
  resources :zones

  resources :audits

  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
    resources :jobs
  end

  namespace :api, defaults: {:format => :json} do
    root :to => 'versions#index'

    resources :versions

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :applications
      resources :application_versions
      resources :servers
      resources :jobs
      resources :inventory_spreadsheets do
        member do
          get :send_via_email
        end
        collection do
          get :generate
        end
      end
      resources :inventory_diagrams do
        member do
          get :send_via_email
        end
        collection do
          get :generate
        end
      end
    end
  end
end

app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
  load_and_authorize_resource

  before_filter :set_database, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @databases = Database.all
    respond_with(@databases)
  end

  def show
    respond_with(@database)
  end

  def new
    @database = Database.new
    respond_with(@database)
  end

  def edit
  end

  def create
    @database = Database.new(params[:database])
    @database.save
    respond_with(@database)
  end

  def update
    @database.update_attributes(params[:database])
    respond_with(@database)
  end

  def destroy
    @database.destroy
    respond_with(@database)
  end

  private
    def set_database
      @database = Database.find(params[:id])
    end
end

app/helpers/databases_helper.rb
module DatabasesHelper
end

app/views/databases/_form.html.erb
<%= form_for(@database) do |f| %>
    <% if @database.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@database.errors.count, "error") %> prohibited this database from being saved:</h2>

          <ul>
            <% @database.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :dbms, t('databases.dbms') %><br />
      <%= f.text_field :dbms %>
    </div>
    <div class="field">
      <%= f.label :application %><br />
      <%= f.collection_select :application_id, Application.order(:name),:id,:name, { :include_blank => true} %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/databases/edit.html.erb
<h1><%= t('general.editing') % @database.name %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Show', @database %> |
<%= link_to 'Back', databases_path %>

app/views/databases/index.html.erb
<h1><%= t('general.listing') % t('databases.databases') %></h1>

<table id='index_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('databases.name') %></th>
    <th><%= t('databases.dbms') %></th>
    <th><%= t('applications.application') %></th>
  </tr>
  </thead>
  <tbody>
  <% @databases.each do |database| %>
      <tr>
        <td><%= link_to database.name, database %></td>
        <td><%= database.dbms %></td>
        <td><%= link_to(database.application.name, database.application) if database.application %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br />
<br />
<div>
  <%= t('general.download') %>: <%= link_to t('general.csv'), databases_path(format: 'csv') %>
</div>

app/views/databases/new.html.erb
<h1><%= t('general.new') % t('databases.database') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', databases_path %>

app/views/databases/show.html.erb
<h1><%= @database.name.upcase %></h1>
<div class='model_info'>
  <b><%= t('applications.application') %></b>
  <%= @database.application ? @database.application : t('general.not_applicable') %><br/>
  <b><%= t('databases.dbms') %></b>
  <%= @database.dbms %><br/>
  <br />
  <b><%= t('general.created_on') %>:</b>
  <%= @database.created_at.to_formatted_s(:long_ordinal) %><br/>
  <b><%= t('general.updated_on') %>:</b>
  <%= @database.updated_at.to_formatted_s(:long_ordinal) %><br/><br/><br/>
</div>
<br/><br/><br/>

<%= link_to t('general.back'), :back %>