config/routes.rb
Inventory::Application.routes.draw do
  resources :server_applications


  authenticated :user do
    root :to => 'inventory_spreadsheets#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')


  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :my_account, :controller => :my_account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
    resources :jobs
  end

  resources :inventory_spreadsheets do
    member do
      get :new_email
      get :send_via_email
    end
    collection do
      get :generate
    end
  end

  resources :inventory_diagrams do
    member do
      get :new_email
      get :send_via_email
    end
    collection do
      get :generate
      get :show_generate
    end
  end
  resources :applications
  resources :application_versions
  resources :servers
  resources :application_family_applications
  resources :application_families
  resources :server_databases
  resources :databases
  resources :server_relationships
  resources :jobs
  resources :tenant_spaces
  resources :data_centers
  resources :environments
  resources :zones

  resources :audits

  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
    resources :jobs
  end

  namespace :api, defaults: {:format => :json} do
    root :to => 'versions#index'

    resources :versions

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :applications
      resources :application_versions
      resources :servers
      resources :jobs
      resources :inventory_spreadsheets do
        member do
          get :send_via_email
        end
        collection do
          get :generate
        end
      end
      resources :inventory_diagrams do
        member do
          get :send_via_email
        end
        collection do
          get :generate
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :secure => (AppConfig.get(%w(user_profiles secure), APP_CONFIG) ? AppConfig.get(%w(user_profiles secure), APP_CONFIG) : false)

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable,
         :timeoutable

  devise :omniauthable, :omniauth_providers => [:auth_man]

  include RoleModel

  DEFAULT_ROLES = [
      :normal_user
  ]

  ROLE_DESCRIPTIONS = {
      :admin                            => 'Can administrate the system.',
      :normal_user                      => 'Default role.',
      :inventory_diagram_generator      => 'Can generate InventoryDiagrams.',
      :inventory_spreadsheet_generator  => 'Can generate InventorySpreadsheets.'
  }
  roles_attribute :roles_mask
  roles ROLE_DESCRIPTIONS.keys

  before_create :add_default_roles

  attr_accessible :email, :fname, :lname, :password, :time_zone, :roles

  has_many :applications
  has_many :application_versions
  has_many :servers
  has_many :data_centers
  has_many :environments
  has_many :tenant_spaces
  has_many :zones
  has_many :server_applications

  has_many :inventory_spreadsheets
  has_many :inventory_diagrams

  has_many :jobs

  def to_s
    self.name
  end

  def self.from_omniauth(auth)
    user_return = where(provider: auth.provider, uid: auth.uid).first

    unless user_return
      user = User.new(
          :email        => auth.info.email,
          :password     => Devise.friendly_token[0,20],
          :fname        => auth.info.fname,
          :lname        => auth.info.lname,
          :time_zone    => auth.info.time_zone,
      )

      user.uid      = auth.uid
      user.provider = auth.provider

      user.skip_confirmation!
      user.save

      user_return = user
    end

    user_return.sync_with_omniauth(auth)

    user_return
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.auth_man_data'] && session['devise.auth_man_data']['extra']['raw_info']
        user.email      = data['email'] if user.email.blank?
        user.fname      = data['fname'] if user.fname.blank?
        user.lname      = data['lname'] if user.lname.blank?
        user.time_zone  = data['time_zone'] if user.time_zone.blank?
      end
    end
  end

  def sync_with_omniauth(auth)
    unless auth.info.fname == self.fname && auth.info.lname == self.lname && auth.info.time_zone == self.time_zone
      self.fname      = auth.info.fname
      self.lname      = auth.info.lname
      self.time_zone  = auth.info.time_zone

      self.save
    end
  end

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def full_name
    self.fname && self.lname ? "#{self.fname} #{self.lname}" : nil
  end

  def full_name_comma
    self.fname && self.lname ? "#{self.lname}, #{self.fname}" : nil
  end

  def name
    self.fname && self.lname ? "#{self.fname} #{self.lname}" : self.email
  end

  private
  def valid_roles
    if self.roles_mask.nil? || self.roles_mask < 1
      errors.add(:base, 'At least one role must be selected')
    end
  end

  def add_default_roles
    DEFAULT_ROLES.each do |role|
      self.roles << role unless self.has_role?(role)
    end

    AppConfig.get(%w(user_profiles default_roles), APP_CONFIG).each do |role|
      self.roles << role.to_sym unless self.has_role?(role.to_sym) || !User.valid_roles.include?(role.to_sym)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  load_and_authorize_resource

  def index
    @users = User.all.select{ |user| user.email != User.find(ANONYMOUS_USER_ID).email }
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @roles = User.valid_roles
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = t('admin.users.created_user')
      redirect_to admin_users_path
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @roles = @user.roles
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?

    params[:user][:roles] = Array.new if params[:user][:roles].nil?

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to session[:user_return_to] ? session[:user_return_to] : admin_users_path, notice: t('admin.users.updated_user') }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user == @user
      flash[:alert] = t('admin.users.cannot_delete')
    elsif @user.destroy
      flash[:notice] = t('admin.users.deleted_user')
    end

    respond_to do |format|
      format.html { redirect_to admin_users_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def auth_man
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      session['devise_omniauth_myaccount'] = request.env['omniauth.auth'].info.my_account
      session['devise_omniauth_enable_gravatar'] = request.env['omniauth.auth'].info.enable_gravatar
      session['devise_login_type'] = :omniauth

      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => 'AuthMan') if is_navigational_format?
    else
      raise Exception.new('Failed to create or find user.')
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/admin/users/_form.html.erb
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, :autofocus => true %>
    </div>
    <div class="field">
      <%= f.label :fname %><br />
      <%= f.text_field :fname %>
    </div>
    <div class="field">
      <%= f.label :lname %><br />
      <%= f.text_field :lname %>
    </div>
    <div class="field">
      <%= f.label :roles %>
      <ul>
        <% User.valid_roles.sort.each do |role| %>
            <% role_hash = role_formatted(role) %>
            <li id="role_<%= role %>"><%= check_box_tag 'user[roles][]', role, @user.roles.include?(role) %> <%= role_hash[:name] %> - <%= role_hash[:description] %></li>
        <% end %>
      </ul>
    </div>

app/views/admin/users/edit.html.erb
<h1><%= t('general.actions.edit') % @user.email.upcase %></h1>

<%= form_for(@user, :url => admin_user_path) do |f| %>
    <%= render 'form', f: f %>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit t('admin.users.update_user') %>
    </div>
<% end %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'),:back %>

app/views/admin/users/index.html.erb
<br />
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('user.users') %>
  </div>
  <div class="panel-body">
    <table class='data_table' id="server_groups_table">
      <thead>
      <tr>
        <th><%= t('admin.users.email_address') %></th>
        <th><%= t('user.name') %></th>
        <th><%= t('admin.users.created') %></th>
        <th><%= t('admin.users.last_login') %></th>
        <th><%= t('general.actions.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr id="user_<%= user.id %>">
            <td><%= link_to user.email, admin_user_path(user) %></td>
            <td> <%= user.name %></td>
            <td><%= user.created_at.strftime(t('general.timestamp_to_str')) %></td>
            <td><%= user.last_sign_in_at ? user.last_sign_in_at.strftime(t('general.timestamp_to_str')) : t('general.not_applicable') %></td>
            <td>
              <%= link_to t('general.actions.edit'), edit_admin_user_path(user) %>
              <% if current_user != user %>
                  <%= link_to t('general.actions.delete'), admin_user_path(user), :confirm => t('general.are_you_sure'), :method => :delete %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if can? :create, User %>
    <span class='actions'>
      <%= link_to t('general.actions.new'), new_admin_user_path, :id => 'new_admin_user_link' %>
    </span>
<% end %>

app/views/admin/users/new.html.erb
<h1><%= t('general.new') % t('user.user') %></h1>

<%= form_for(@user, :url => admin_users_path) do |f| %>
    <%= render 'form', f: f %>

    <div class="actions">
      <%= f.submit t('admin.users.send_confirmation_instructions') %>
    </div>
<% end %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'), :back %>

app/views/admin/users/show.html.erb
<h1><%= @user.full_name %></h1>
<%= render 'my_account/my_account', :user => @user, :gravatar_url => current_user.gravatar_url(:size => 64) %>
<br />
<br />
<%= link_to t('general.actions.edit'), edit_admin_user_path(@user) %>